### ISSUE TITLE
Group profile Image doesn't resize correctly

### ISSUE THREAD

**Issue by tylerbhughes** [urbanengine/OpenHuntsville#111]
The stock group profile image is rendered at 160x160 pixels. If an image uploaded is larger than that it then it isn't rendered correctly on the page. I talked with Drew about this and he believes it's due to the aspect ratio. One of his suggestions was that we could take the image when it is uploaded, make as many copies as needed and resize one of the copies to work with our site. He mentioned using **ImageMagick** or one of the libraries that uses it.

**Comment by davidhjones** [comment]
We temporarily removed the seed images. As part of this enhancement we should introduce the AWS image upload functionality for Groups. This may mitigate the original issue.

**Comment by tylerbhughes** [comment]
While working on issue #143 I found out that there's actually a progress bar that's part of the image upload functionality but either some CSS or some JS is preventing it from displaying when the user uploads their files.

**Comment by tylerbhughes** [comment]
As part of our roadmap we are working on a new .NET and React site to replace the existing Ruby and Pakyow site. As part of this transition, this enhancement has been removed from our roadmap.
