### ISSUE TITLE
Add Ruby model dependency for foreign keys

### ISSUE THREAD

**Issue by davidhjones** [urbanengine/OpenHuntsville#115]
Currently if you try to delete an event that has a child event, you'll get a Pakyow error, because it will orphan the child event. There is capability in Sequel to add `dependency: :nullify` in the Models, but I haven't been able to get it to work. Need to make this work, such that, when a parent event is deleted, the child event's `parent_id` column is set to null

**Comment by skylenewman** [comment]
If a parent is deleted, is a child still valid?

**Comment by RandomlyKnighted** [comment]
Yes, the parent column is optional. For example if Designer's Corner is hosted by CoWorking Night then CoWorking Night would be the parent. If for some reason we had to postpone CoWorking Night for a week  we don't want to delete their event.

**Comment by davidhjones** [comment]
In @RandomlyKnighted's scenario the expected result is the CoWorking Night event would be deleted, and the Designers Corner's event's `parent_id` column should be set to null.

**Comment by davidhjones** [comment]
Currently with our Sequel Model configuration the CoWorking Night event cannot be deleted until the Designers Corner event is deleted (because DC event has a dependency on CWN event)

**Comment by davidhjones** [comment]
Related to #129

**Comment by tylerbhughes** [comment]
As part of our roadmap we are working on a new .NET and React site to replace the existing Ruby and Pakyow site. As part of this transition, this enhancement has been removed from our roadmap.
