### ISSUE TITLE
Fix misc text to better reflect current state of the app.

### ISSUE THREAD

**Issue by davidhjones** [urbanengine/OpenHuntsville#119]
For 1. I noticed this text "Don't see your industry category listed? Let us know via the contact form in the lower right." We don't have a contact form anymore. Should probably go through and check all text to make sure it still makes sense.

**Comment by tylerbhughes** [comment]
As part of our roadmap we are working on a new .NET and React site to replace the existing Ruby and Pakyow site. As part of this transition, this enhancement has been removed from our roadmap.
