### ISSUE TITLE
Create a rolling horizon for the manage events page

### ISSUE THREAD

**Issue by tylerbhughes** [urbanengine/OpenHuntsville#124]
We are seeding CoWorking Night events up to a given date in the future. This can cause the Manage Events page to get crowded with events that don't have to be reviewed (approved). Really I only need to see the events for the next 2-36 weeks. Anything beyond that I don't need to see until it gets closer to that week. 

This should only apply to site admins, because as we expand to support groups outside of New Leaf Digital people will want to be able to plan their events months in advance.

> Rolling Horizon - its a rolling window; It's like saying show the events that have a start_datetime from now until the next 3 months

**Comment by davidhjones** [comment]
To round out this feature the rolling horizon should be configurable from the UI perspective to choose how far out you would like to see events for

**Comment by tylerbhughes** [comment]
As part of our roadmap we are working on a new .NET and React site to replace the existing Ruby and Pakyow site. As part of this transition, this enhancement has been removed from our roadmap.
