### ISSUE TITLE
Extra space below footer logo

### ISSUE THREAD

**Issue by chrisbeaman** [urbanengine/OpenHuntsville#155]
On my screen, there's a lot of extra space below the footer logo. Looks like it's because of the "50vh" height assignment to .originals.

![image](https://user-images.githubusercontent.com/184221/30050076-ae696836-91e2-11e7-8b8b-5179c2c3f363.png)

**Comment by tylerbhughes** [comment]
@chrisbeaman what is your screen resolution?

**Comment by tylerbhughes** [comment]
@chrisbeaman thanks, Oddly enough when I use that resolution it looks fine. What browser are you using? I wonder if it has to do with how the browser handles the units.

**Comment by chrisbeaman** [comment]
Hmm, that is odd. I'm using Chrome on a Mac.

**Comment by tylerbhughes** [comment]
Hmm, I'll test it out on my Mac when I get home. Could be the difference in Chrome on PC vs Mac. If it is then I'm not sure how to fix that.

**Comment by chrisbeaman** [comment]
They have you running PCs over there at Hexagon? Sheesh - hope they upgrade your computer soon! ;)

**Comment by tylerbhughes** [comment]
As part of our roadmap we are working on a new .NET and React site to replace the existing Ruby and Pakyow site. As part of this transition, this enhancement has been removed from our roadmap.
