### ISSUE TITLE
Redirected to OptIn instead of 401 on Unauthorized Links when Logged In

### ISSUE THREAD

**Issue by CBWallace01** [urbanengine/OpenHuntsville#159]
When logged in, hitting a link that should throw a 401 redirects the user to the OptIn screen.

**Comment by tylerbhughes** [comment]
@CBWallace01 can you give an example of when this happens?

**Comment by tylerbhughes** [comment]
As part of our roadmap we are working on a new .NET and React site to replace the existing Ruby and Pakyow site. As part of this transition, this bug has been removed from our roadmap.
