### ISSUE TITLE
Expose Canceled property in Flyer API

### ISSUE THREAD

**Issue by davidhjones** [urbanengine/OpenHuntsville#160]
- Change the button for Group Admin / Site Admins to set the `archived` column, and read "Cancel"
- Update `archived` column to `canceled`
- Expose `canceled` column in Flyer API. Should read `canceled`, with the value `true` or `false`
- Make Delete button, shown for Site Admins, to hard-delete an event

Nice to have:
- Only update `canceled` field to true, **after** the event has been approved. If the event has **not** been approved, the Cancel button will hard-delete the event.

**Comment by tylerbhughes** [comment]
This is complete. In v2 of the API I exposed isCancelled property for each event.
