### ISSUE TITLE
Expose Updated property in Flyer API

### ISSUE THREAD

**Issue by davidhjones** [urbanengine/OpenHuntsville#161]
Basically the way this property should operate is as follows:

- This property only comes into scope once an event has been approved.
- Once approved, the Event's `updated` field is false.
- After that, if any property that is exposed on the flyer (Title, Description, Group Name, Category, Venue, Time) change, `updated` is set to true.

The end goal is meant to be useful for a user that has visited the flyer once and seen a event. Once they return to the flyer a second time, we want to highlight to them that some properties on this event have changed. Therefore, we should make sure that we encapsulate the logic which sets this value to true to only include a workflow that meets this user story.

- This is probably accomplished easiest by adding a new column in the database specifically for this mechanism. Although, it may be possible to converge this idea in with the update properties already existing in the database.

Things to think about:
- Possibly need to make it configurable (with a simple check box) for SiteAdmins, so that if you need to change something but do not want to set `updated` to true, it can be manually changed?

**Comment by tylerbhughes** [comment]
You mentioned having a checkbox for admins. If we went this route it should probably something on the lines of "Override updated field" so that the logic for that can be that if it's checked then you ignore the logic for the updated field.

**Comment by tylerbhughes** [comment]
As part of our roadmap we are working on a new .NET and React site to replace the existing Ruby and Pakyow site. As part of this transition, this enhancement has been removed from our roadmap.
