### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by skylenewman** [urbanengine/OpenHuntsville#35]
Add a sorting function (A-Z, Z-A, recently added, longest on site, etc) on the people list pages

**Comment by chrisbeaman** [comment]
Also consider adding self-defined tags to profiles.

**Comment by tylerbhughes** [comment]
As part of our roadmap we are working on a new .NET and React site to replace the existing Ruby and Pakyow site. As part of this transition, this enhancement has been removed from our roadmap.
