### ISSUE TITLE
Configure CSS minify functionality into Rake task

### ISSUE THREAD

**Issue by skylenewman** [urbanengine/OpenHuntsville#6]
1. Find and configure CSS minify functionality
2. Add to Rake task to run before deploy
3. Modify bindings to use normal CSS locally and the minified version in production.

A couple of quick Google searches yielded these possible solutions, but implementer is not limited to these projects:
- https://github.com/mcollina/rake-minify
- https://github.com/matthiassiegel/cssminify

**Comment by tylerbhughes** [comment]
There are a ton of CSS/JS files some of which look like were only used for one or two small things. If we want to do this then its should probably wait to happen until #143 is finished.

**Comment by tylerbhughes** [comment]
As part of our roadmap we are working on a new .NET and React site to replace the existing Ruby and Pakyow site. As part of this transition, this enhancement has been removed from our roadmap.
