### ISSUE TITLE
Configure FastLink

### ISSUE THREAD

**Issue by skylenewman** [urbanengine/OpenHuntsville#66]
Change application links to use `data-ui="fastlink"`. This will load pages through the WebSocket, improving performance on subsequent page loads. Depends on #65.
- https://github.com/pakyow/ring
- http://forums.pakyow.org/t/avoid-page-refresh-with-links/28

**Comment by tylerbhughes** [comment]
As part of our roadmap we are working on a new .NET and React site to replace the existing Ruby and Pakyow site. As part of this transition, this enhancement has been removed from our roadmap.
