### ISSUE TITLE
Add JS validation to /people/new

### ISSUE THREAD

**Issue by skylenewman** [urbanengine/OpenHuntsville#71]
1. Check if email address is already in system
2. Check if passwords match
3. Check if password follows best practices with http://plugins.jquery.com/pwstrength/
4. Style plugin to look something like the attached (use colors #e1000; #feea50; #00b830)

![password-weak](https://cloud.githubusercontent.com/assets/1457762/17273157/2241db8e-5671-11e6-8fab-ebe3208c21bd.png)
![password-strong](https://cloud.githubusercontent.com/assets/1457762/17273161/39b3a9a0-5671-11e6-918b-ba941bb40645.png)

**Comment by tylerbhughes** [comment]
As part of our roadmap we are working on a new .NET and React site to replace the existing Ruby and Pakyow site. As part of this transition, this enhancement has been removed from our roadmap.
