### ISSUE TITLE
Change meta description on About page

### ISSUE THREAD

**Issue by skylenewman** [urbanengine/OpenHuntsville#72]
Change to "Open Huntsville is an open directory of independent professionals who provide their services to help fellow Huntsville-based businesses grow."

Currently, we are binding the `<meta description>` element in `app/lib/bindings/head.rb`.

**Comment by tylerbhughes** [comment]
As part of our roadmap we are working on a new .NET and React site to replace the existing Ruby and Pakyow site. As part of this transition, this enhancement has been removed from our roadmap.
