### ISSUE TITLE
Add element to header 

### ISSUE THREAD

**Issue by skylenewman** [urbanengine/OpenHuntsville#73]
Suggested implementation path:
1. Create a partial that includes a `<div class="hidden" data-scope="hello" data-prop="div">...</div>`. It would also need to include a `data-prop` to bind the user's name to.
2. Add that partial to the different templates.
3. Add logic that checks if the current user is authenticated. If the user is authenticated, the function should change the CSS class of the outer `data-prop` to `visible` and bind the current user's first name and last name to the inner `data-prop`. This should be done for every route, most likely by using a shared route and calling it `:before =>` the route's logic.

![open-hsv-hello-user-mockup](https://cloud.githubusercontent.com/assets/1457762/17779183/5e80a52a-652c-11e6-98df-fb9b38ab3fc7.png)

**Comment by tylerbhughes** [comment]
As part of our roadmap we are working on a new .NET and React site to replace the existing Ruby and Pakyow site. As part of this transition, this enhancement has been removed from our roadmap.
