### ISSUE TITLE
Move the reset password functionality from the profile edit screen

### ISSUE THREAD

**Issue by skylenewman** [urbanengine/OpenHuntsville#75]
Currently, users can reset their password on the profile edit screen. Since it is using a common partial, this also shows up when users are creating their profiles. This needs to go to another screen.

Possible Implementation
1. Create a view (HTML file) in `app/views/people/`
2. Add a header, form in the new view with `data-scope="people" data-prop="action"`, and "Reset Password" button in the new view.
3. Cut and paste the password reset `fieldset` from `app/views/people/_form.html` into the new view.
4. Create a `get` route for the new view.
5. Update the `action :update` route to only assign values if they are in the `params[:people][<field-name>]`. For instance, don't `people.first_name = params[:people][:first_name]` if the parameter is nil or has no length.
6. Verify that the form submits to the `action :update` route and the password is updated

**Comment by tylerbhughes** [comment]
With the addition of Auth0 this is no longer relevant.
