### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by skylenewman** [urbanengine/OpenHuntsville#83]

**Comment by RandomlyKnighted** [comment]
@skylenewman is this a password reset if you're already logged into the account?

**Comment by skylenewman** [comment]
No. It sends a token to the email account and resets while you're
unauthenticated.

###
Kyle Newman
Software and Website Design and Development
cell: 205.270.9230

**Comment by tylerbhughes** [comment]
@skylenewman did you ever commit your code for this? I'm still interested in getting this functionality added. Even if it's in a branch on it's own I'm happy to review it and get it added. If it's not finished just let me know what I need to do to get it working.

**Comment by tylerbhughes** [comment]
Per Kyle, this is how he planned to implement the password reset:

> At the moment, no. I have not put the project onto Github. Basically, user requests reset, app checks for email address in DB. If email address is valid, app creates token record with ID and valid until timestamp. Email or text sent with token and/or URL. On page to change password, app checks if token/code is valid and within timestamp before changing password and authenticating.

**Comment by tylerbhughes** [comment]
Password resets are now handled by Auth0 and no longer relevant.
