### ISSUE TITLE
Add notification letting user know if profile edit succeeded or failed

### ISSUE THREAD

**Issue by tylerbhughes** [urbanengine/OpenHuntsville#88]

**Comment by davidhjones** [comment]
Seems like the best way to achieve this is with redirect status codes (https://www.pakyow.org/docs/helpers/redirecting). I think we can catch the code in the redirect and handle accordingly in the view to send off the correct toastr notification

**Comment by tylerbhughes** [comment]
As part of our roadmap we are working on a new .NET and React site to replace the existing Ruby and Pakyow site. As part of this transition, this enhancement has been removed from our roadmap.
